language: java
env:
  global:
    - CODECOV_TOKEN="81b6a8e8-7f58-41af-acae-e021c08b36e2"
notifications:
  email:
    on_success: always
    on_failure: always
after_success:
    - bash <(curl -s https://codecov.io/bash)
